### ISSUE TITLE
Javascript vs. Python Version

### ISSUE THREAD

**Issue by skilfullycurled** [stared/tagoverflow#3]
Hi,

Thanks for this great visualization technique.  I already used the python implementation for a learning community I belong to and it worked out great (I think):

https://publiclab.org/notes/liz/09-15-2016/first-draft-of-tag-graph

Can I trouble you to provide some direction on where the equivalent javascript code is for some of the functions in the python version? In particular, [calculate_pair_weights](https://github.com/stared/tag-graph-map-of-stackexchange/blob/fd6098e651c1038d030bad93b9324b76723da2d0/tag_bundle_processing.py#L44), [bundles2tags](https://github.com/stared/tag-graph-map-of-stackexchange/blob/fd6098e651c1038d030bad93b9324b76723da2d0/tag_bundle_processing.py#L54), and [bundles2pairs](https://github.com/stared/tag-graph-map-of-stackexchange/blob/fd6098e651c1038d030bad93b9324b76723da2d0/tag_bundle_processing.py#L63).

Additionally, if one didn't need the bells and whistles of the UI you created for the javascript version, do you think a more direct translation of the python version to javascript would still work, or are there somethings which don't directly translate and require major rewrites?

Thanks for your help, and this work!

**Comment by stared** [comment]
@skilfullycurled  Not sure if I understand what you mean. This repo is purely JS. It is not a direct rewrite of `tag-graph-map-of-stackexchange`. It achieves a similar goal, but starts with data in a slightly different format. https://github.com/stared/tagoverflow/blob/gh-pages/se_tags.js#L233 is the closest equivalent of tag processing from the Python file.

Feel free to rewrite JS to Python or vice versa.  Won't do that for you.

(Closed as it is NOT an issue.)

**Comment by skilfullycurled** [comment]
Ah, I see.  It's not a "translation" of one version to the other.

> Feel free to rewrite JS to Python or vice versa. Won't do that for you.

I want to make one thing clear.  I in no way meant to imply that you should do any of the re-writing.  In fact, just the opposite, I was looking for concurrence between the two so that *I* could do an implementation.  My apologies for any confusion on that end.  As I hope I imparted, I'm very grateful to you for what you have written!
